name: Pipeline GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  cicd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalação de Módulos que são necessários para a Aplicação
        run: |
          pip install flask

      - name: Test
        run: |
          python -m pytest test.py
